"""crashbytes-strutils — Zero-dependency string utilities."""

from crashbytes_strutils._core import (
    between,
    count_words,
    initials,
    is_blank,
    is_valid_email,
    mask,
    pad_left,
    pad_right,
    remove_whitespace,
    reverse,
    slugify,
    strip_html,
    to_camel_case,
    to_constant_case,
    to_kebab_case,
    to_pascal_case,
    to_snake_case,
    to_title_case,
    truncate,
)

__all__ = [
    "between",
    "count_words",
    "initials",
    "is_blank",
    "is_valid_email",
    "mask",
    "pad_left",
    "pad_right",
    "remove_whitespace",
    "reverse",
    "slugify",
    "strip_html",
    "to_camel_case",
    "to_constant_case",
    "to_kebab_case",
    "to_pascal_case",
    "to_snake_case",
    "to_title_case",
    "truncate",
]
